//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeDesktop
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderStatus
    {
        public int IdStatus { get; set; }
        public string OrderStatus1 { get; set; }
    }
}
